config/routes.rb
Rails.application.routes.draw do

  get 'ship/new'
  get 'ship/index'
  get 'ship/edit'
  devise_for :users#, controllers: { registrations: 'registrations' }

  namespace :admin do
    get "/"=>"root#top"

    resources :users,only: [:index]
    resources :cds
    resources :artists
    resources :requests,only: [:index]
  end

    get '/top' => 'roots#top'
    root 'roots#top'
    resources :cds
    resources :artists,only: [:index, :show] do
        resources :favorites,only: [:create,:destroy]
    end
    resources :carts do
       resources :cartitems
    end
    post '/cartitems' => 'cartitems#create' , as: 'cartitem_create'

    resources :users,only: [:show,:edit,:update,:destroy] do
        get '/favorites' =>'users#favorites'
        resources :requests,only:[:create,:new, :destroy]
        resources :boughts do
          resources :boughtitems
        end
    end

    resources :ships

    get '/cd_search' =>'cds#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :cds, inverse_of: :artist, dependent: :destroy
	has_many :favorites, dependent: :destroy
	accepts_nested_attributes_for :cds
	attachment :image
	has_many :users, through: :favorites

	def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Artist.where(['name LIKE ?', "%#{search}%"])
	    end
	end

	# def favorited_by?(user)
          # favorites.where(user_id: user.id).exists?
    # end

end

app/models/bought.rb
class Bought < ApplicationRecord
	belongs_to :user#, optional: true
	has_many :boughtitems, dependent: :destroy

	enum status: { in_preparation: 0, shipped: 1, delivery_completed: 2}
	enum ship: { home: 0, new: 1, registered1: 2}, _suffix: true

	def total_price
		boughtitems.to_a.sum { |item| item.total_price }
	end

	default_scope -> { order(created_at: :desc) }
end

app/models/boughtitem.rb
class Boughtitem < ApplicationRecord
	belongs_to :bought
	belongs_to :cd

	def total_price
		cd.price * quantity
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user, optional:true
	has_many :cartitems, dependent: :destroy, inverse_of: :cart
    accepts_nested_attributes_for :cartitems, reject_if: :all_blank, allow_destroy: true

	def add_cd(cd_id)

		current_item = cartitems.find_by_cd_id(cd_id)

		if current_item
			current_item.quantity += 1
		else
			current_item = cartitems.build(cd_id: cd_id)
		end
		current_item

	end

	def total_price
		cartitems.to_a.sum { |item| item.total_price }
	end

end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
	belongs_to :cart, optional:true, inverse_of: :cartitems
	belongs_to :cd, optional:true

	def total_price
		cd.price * quantity
	end
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :artist, optional:true, inverse_of: :cds
	has_many :discs, inverse_of: :cd
	has_many :boughtitems
	has_many :cartitems
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true
	attachment :image

  enum genre: { J_pop: 0, Roock: 1, EDM: 2, Metal: 3, Jazz: 4, Classic: 5, Country: 6, Rap: 7 }


 def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       Cd.where(['genre LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    end
 end

	# 商品を破棄する際のフックメソッドを登録する
    # destroy()が実行される前に、Railsが自動的に実行する
    # 戻り値がfalseであれば、destroy()は実行されない
    # (リフレクションで呼出されるらしい)
    before_destroy :referenced_by_cartitem

    private

    def referenced_by_cartitem
      # 関連する品目が空でないか検証
      if cartitems.empty?
        return true
      else
        errors.add(:base, "品目が存在します")
        return false
      end
    end

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :cd, inverse_of: :discs
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :artist

	validates :artist_id, :uniqueness => {:scope => :user_id}
	# validates :user_id, :uniqueness => {:scope => :article_id}

end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/ship.rb
class Ship < ApplicationRecord
	belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc, inverse_of: :songs


def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
    	Song.where(['name LIKE ?', "%#{search}%"])


    end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable;

         has_many :requests
         has_many :carts
         has_many :favorites
         has_many :boughts
         has_many :ships
         has_many :artists, through: :favorites
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
  before_action :admin

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.new(artist_params)
    artist.save
    redirect_to artist_path(artist.id), notice: '登録完了'
  end

  def show
    @artist = Artist.find(params[:id])
    @cds = Cd.where(artist_id: @artist.id)
    redirect_to artist_path(artist.id)
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    artist = Artist.find(params[:id])
    # binding.pry
    artist.update(artist_params)
    redirect_to artist_path(artist.id), notice: '変更完了'
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to admin_path, notice: '削除完了'
  end

  private
   def artist_params
    params.require(:artist).permit(:name, :label, :hp, :twitter_code, :image, :reccomend, :copy, :intro)
   end

   def admin
       if user_signed_in?
         if current_user.admin?
         else
           redirect_to root_path
         end
       else
         redirect_to root_path
       end
   end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.order("proceed DESC")
    
  end

  def show
    @artist = Artist.find(params[:id])
    @cds = Cd.where(artist_id: @artist.id)
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    # binding.pry
    
  end
end

app/helpers/admin/artists_helper.rb
module Admin::ArtistsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/ship_helper.rb
module ShipHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/artists/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h3>アーティスト編集画面</h3>
            <div class="form_artist_edit">
                <%= bootstrap_form_for(@artist, url: admin_artist_path, method: :patch) do |f| %>
                    <%= f.text_field :name, label: "アーティスト名" %><br>
                    <%= f.text_area :copy, label: "キャッチコピー" %><br>
                    <%= f.text_area :intro, label: "紹介文" %><br>
                    <%= f.text_field :label, label: "レーベル名" %><br>
                    <%= f.text_area :hp, label: "公式サイトのURL" %><br>
                    <%= f.text_area :twitter_code, label: "ツイッター埋め込みコード ※height:1000px" %><br>
                    <a href=https://publish.twitter.com/# target="_blank">埋め込みコードの取得はこちらから</a><br><br><br>
                    <label>アーティスト画像</label><br>
                    <%= attachment_image_tag @artist, :image, :fill, 60, 60 %>
                    <%= f.attachment_field :image, placeholder: "プロフィール画像" %><br><br><br>
                    <%= f.submit "変更を保存"%>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/artists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3>アーティスト一覧</h3>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
           <th>ID No.</th>
           <th>アーティストイメージ</th>
           <th>アーティスト名</th>
           <th>レーベル名</th>
           <th>売上</th>
           <th><i class="fas fa-heart"></i></th>
           <th>HP</th>
           <th>Twitter</th>
           <th>Copy</th>
           <th>Intro</th>
         </tr>
        </thead>

       <% @artists.each do |a| %>
          <tbody>
           <tr>
            <td>
                <%= a.id %>
            </td>
            <td><%= attachment_image_tag a, :image, size: '30x30', format: 'jpeg', class: "", fallback: "no_image.png", alt: "No image" %></td>
            <td><%= link_to a.name, artist_path(a.id) %></td>
            <td><%= a.label %></td>
            <td><%= a.proceed %></td>
            <td><%= a.favorites.count %></td>
            <td><% if a.hp.present? %>
                  o
                <% else %>
                  x
                <% end %>
            </td>
            <td><% if a.twitter_code.present? %>
                  o
                <% else %>
                  x
                <% end %>
            </td>
            <td><% if a.copy.present? %>
                  o
                <% else %>
                  x
                <% end %>
            </td>
            <td><% if a.intro.present? %>
                  o
                <% else %>
                  x
                <% end %>
            </td>

            <td><%= link_to "編集", edit_admin_artist_path(a.id) %></td>
            <td>
               <%= link_to "削除", admin_artist_path(a.id),
                method: :delete,  data: { confirm: '削除してよろしいですか？' } %>
            </td>
           </tr>
          </tbody>
       <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/artists/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h3>新規アーティスト登録</h3>

                <div class="form_artist_new">
                    <%= bootstrap_form_for(@artist, url: admin_artists_path, method: :post) do |f| %>
                        <%= f.text_field :name, label: "アーティスト名" %>
                        <%= f.text_field :label, label: "レーベル名" %>
                        <%= f.text_field :copy, label: "キャッチコピー" %>
                        <%= f.text_area :intro, label: "紹介文" %>
                        <%= f.text_field :hp, label: "公式サイトのURL" %>
                        <%= f.text_field :twitter_code, label: "ツイッター埋め込みコード ※height:1000px" %>
                        <a href=https://publish.twitter.com/# target="_blank">埋め込みコードの取得はこちらから</a><br><br>
                        <label>アーティスト画像</label><br>
                        <%= f.attachment_field :image,label: "アーティスト画像" %><br><br><br>
                        <%= f.submit '保存'%>
                    <% end %>
                </div>
        </div>
    </div>
</div>

app/views/artists/index.html.erb
<section class="artist-search">
	<h3>Artists Index</h3>

	<div class="a-s-form">
		<%= form_tag cd_search_path, :method => 'get' do %>
		<div class="input-group">
		    <%= text_field_tag :search, params[:search], class:"form-control" %>
		    <span class="input-group-btn">
		    	<%= submit_tag "Search", :name => nil, class:"btn btn-default"%>
			</span>
	    </div>
		<% end %>
	</div>
</section>
<section class="artist-index">
	<div class="a-i-container clearfix">
		<% @artists.each do |artist| %>
		<div class="a-i-box">
			<%= link_to artist_path(artist.id), :target=>["_blank"] do %>
				<%= attachment_image_tag artist, :image, class:"a-i-image" %>
				<div class="mask">
		       	 <div class="caption">
		          <h5 class="a-i-name"><%= artist.name %></h5>
		         </div>
		        </div>
		</div>
			<% end %>
		<% end %>
	</div>
</section>

app/views/artists/show.html.erb
<div class="artist-main-image-section">

    <div>
      <% if notice %>
       <p id="notice"><%= notice %></p>
      <% end %>
    </div>

	<%= attachment_image_tag @artist, :image, class:"artist-main-image" %>
	<div class="a-m-i-container">
		<h1 class="a-main-image-section-artist-name"><%= @artist.name %>
			<% if user_signed_in? %>
				<% if Favorite.exists?(user_id: current_user.id, artist_id: @artist.id) %>
				<%= link_to artist_favorite_path(@artist), method: :delete do %>
			      <div class="heart icon">
			      	<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					<p>お気に入り</p>
			      </div>
			    <% end %>
				<% else %>
				<%= link_to artist_favorites_path(@artist), method: :post do %>
			      <div class="heart icon">
			      	<i class="fa fa-heart-o" aria-hidden="true"style="color: white;"></i>
					<p>お気に入り</p>
			      </div>
			    <% end %>
				<% end %>
			<% else %>
				<%= link_to new_user_session_path do %>
					<div class="heart icon">
				      	<i class="fa fa-heart-o" aria-hidden="true"style="color: white;"></i>
						<p>お気に入り</p>
				    </div>
			    <% end %>
			<% end %>
		</h1>
	</div>
		<!-- <i class="far fa-heart"></i> -->
</div>
<div class="artist-intro-section">
	<div class="a-intro-container clearfix">
		<div class="a-image-wrap">
			<div class="a-image-box">
				<%= attachment_image_tag @artist, :image, class:"artist-sub-image" %>
			</div>
		</div>
		<div class="a-intro-text">
			<i><h4><strong><%= @artist.copy %></strong></h4></i>
			<p><%= @artist.intro %></p>
			<div class="sub_info">
				<i>
					<p class="artist_label"><%= @artist.label %></p>
					<p class="artist_hp">公式サイト：<%= link_to  @artist.hp, @artist.hp, class:"artist_hp", :target=>["_blank"] %></p>
				</i>
			</div>
		</div>
	</div>
</div>
<div class="artist-contents-section">
	<div class="a-contents-container clearfix">
		<div class="a-twitter">
			<h3>Twitter</h3>
			<div class="a-twitter-box">
				<%= sanitize(@artist.twitter_code) %>
				<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
			</div>
		</div>
		<div class="a-cd-index clearfix">
			<h3>CD</h3>
			<% @cds.each do |cd| %>
				<div class="cd-container">
					<div class="cd-box">
					<%= link_to cd_path(cd.id) do %>
						<%= attachment_image_tag cd, :image, class:"cd-jacket-image" %>
					<% end %>
						<div class="cd-info">
							<h4 class="cd-name"><%= cd.title %></h4>
							<p class="cd-price">¥<%= cd.price %></p>
              				<%= link_to '', cartitem_create_path(cd_id: cd.id), method: :post, class: "i fas fa-cart-arrow-down" %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>
<% if user_signed_in? %>
	<% if current_user.admin? %>
		<div class="artist-show-edit">
			<button type="button" class="btn btn-default"><%= link_to "編集", edit_admin_artist_path(@artist.id) %></button>
			<button type="button" class="btn btn-default"><%= link_to "削除", admin_artist_path(@artist.id), method: :delete %></button>
		</div>
<% end %>
<% end %>