config/routes.rb
Rails.application.routes.draw do

  get 'ship/new'
  get 'ship/index'
  get 'ship/edit'
  devise_for :users#, controllers: { registrations: 'registrations' }

  namespace :admin do
    get "/"=>"root#top"

    resources :users,only: [:index]
    resources :cds
    resources :artists
    resources :requests,only: [:index]
  end

    get '/top' => 'roots#top'
    root 'roots#top'
    resources :cds
    resources :artists,only: [:index, :show] do
        resources :favorites,only: [:create,:destroy]
    end
    resources :carts do
       resources :cartitems
    end
    post '/cartitems' => 'cartitems#create' , as: 'cartitem_create'

    resources :users,only: [:show,:edit,:update,:destroy] do
        get '/favorites' =>'users#favorites'
        resources :requests,only:[:create,:new, :destroy]
        resources :boughts do
          resources :boughtitems
        end
    end

    resources :ships

    get '/cd_search' =>'cds#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :cds, inverse_of: :artist, dependent: :destroy
	has_many :favorites, dependent: :destroy
	accepts_nested_attributes_for :cds
	attachment :image
	has_many :users, through: :favorites

	def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Artist.where(['name LIKE ?', "%#{search}%"])
	    end
	end

	# def favorited_by?(user)
          # favorites.where(user_id: user.id).exists?
    # end

end

app/models/bought.rb
class Bought < ApplicationRecord
	belongs_to :user#, optional: true
	has_many :boughtitems, dependent: :destroy

	enum status: { in_preparation: 0, shipped: 1, delivery_completed: 2}
	enum ship: { home: 0, new: 1, registered1: 2}, _suffix: true

	def total_price
		boughtitems.to_a.sum { |item| item.total_price }
	end

	default_scope -> { order(created_at: :desc) }
end

app/models/boughtitem.rb
class Boughtitem < ApplicationRecord
	belongs_to :bought
	belongs_to :cd

	def total_price
		cd.price * quantity
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user, optional:true
	has_many :cartitems, dependent: :destroy, inverse_of: :cart
    accepts_nested_attributes_for :cartitems, reject_if: :all_blank, allow_destroy: true

	def add_cd(cd_id)

		current_item = cartitems.find_by_cd_id(cd_id)

		if current_item
			current_item.quantity += 1
		else
			current_item = cartitems.build(cd_id: cd_id)
		end
		current_item

	end

	def total_price
		cartitems.to_a.sum { |item| item.total_price }
	end

end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
	belongs_to :cart, optional:true, inverse_of: :cartitems
	belongs_to :cd, optional:true

	def total_price
		cd.price * quantity
	end
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :artist, optional:true, inverse_of: :cds
	has_many :discs, inverse_of: :cd
	has_many :boughtitems
	has_many :cartitems
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true
	attachment :image

  enum genre: { J_pop: 0, Roock: 1, EDM: 2, Metal: 3, Jazz: 4, Classic: 5, Country: 6, Rap: 7 }


 def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       Cd.where(['genre LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    end
 end

	# 商品を破棄する際のフックメソッドを登録する
    # destroy()が実行される前に、Railsが自動的に実行する
    # 戻り値がfalseであれば、destroy()は実行されない
    # (リフレクションで呼出されるらしい)
    before_destroy :referenced_by_cartitem

    private

    def referenced_by_cartitem
      # 関連する品目が空でないか検証
      if cartitems.empty?
        return true
      else
        errors.add(:base, "品目が存在します")
        return false
      end
    end

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :cd, inverse_of: :discs
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :artist

	validates :artist_id, :uniqueness => {:scope => :user_id}
	# validates :user_id, :uniqueness => {:scope => :article_id}

end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/ship.rb
class Ship < ApplicationRecord
	belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc, inverse_of: :songs


def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
    	Song.where(['name LIKE ?', "%#{search}%"])


    end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable;

         has_many :requests
         has_many :carts
         has_many :favorites
         has_many :boughts
         has_many :ships
         has_many :artists, through: :favorites
end

app/controllers/admin/root_controller.rb
class Admin::RootController < ApplicationController
	before_action :admin

	def top
		@artists_p = Artist.order("proceed DESC").limit(10)
		@artists_f = Artist.joins(:favorites).group(:artist_id).order('count(user_id) desc')
	  	@cds = Cd.order("proceed DESC").limit(10)
      @requests = Request.all
	end

    private
    def admin
       if user_signed_in?
         if current_user.admin?
         else
           redirect_to root_path
         end
       else
         redirect_to root_path
       end
    end
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  def top
  	  if user_signed_in?
	  	  if current_user.admin?
	  	  	 redirect_to admin_path, notice: '管理者ログイン完了'
	  	  end
	  end
  	  @artists = Artist.order("proceed DESC").limit(3)
  	  @cds = Cd.order("created_at DESC").limit(4)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/ship_helper.rb
module ShipHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/root/top.html.erb
<!-- <section class="sales">
	<h3>SALES</h3>
	<div class="s-graph">
		<p>できればグラフ表示したいなー。</p>
	</div>
</section> -->
<section class="artist">

	<div>
      <% if notice %>
       <p id="notice"><%= notice %></p>
      <% end %>
    </div>

	<h3>ARTISTS ランキング</h3>
	<div class="a-container clearfix">
		<div class="a-sales">
			<h4>売り上げ順</h4>
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>画像</th>
						<th>アーティスト名</th>
						<th>売り上げ</th>
					</tr>
				</thead>
				<% @artists_p.each do |artist| %>
				<tbody>
					<tr>
						<td>
							<%= artist.id %>
						</td>
						<td><%= attachment_image_tag artist, :image, size: '30x30', format: 'jpeg', class: "", fallback: "no_image.png", alt: "No image" %></td>
						<td><%= link_to artist.name, artist_path(artist.id) %></td>
						<td><%= artist.proceed %></td>
						<td><%= link_to "編集", edit_admin_artist_path(artist.id) %></td>
						<td>
							<%= link_to "削除", admin_artist_path(artist.id),
							method: :delete,  data: { confirm: '削除してよろしいですか？' } %>
						</td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
		<div class="a-favorite">
			<h4>お気に入り順</h4>
			<table class="table">
				<thead>
					<tr>
						<th>ID</th>
						<th>画像</th>
						<th>アーティスト名</th>
						<th>お気に入り数</th>
					</tr>
				</thead>
				<% @artists_p.each do |artist| %>
				<tbody>
					<tr>
						<td><%= artist.id %></td>
						<td><%= attachment_image_tag artist, :image, size: '30x30', format: 'jpeg', class: "", fallback: "no_image.png", alt: "No image" %></td>
						<td><%= link_to artist.name, artist_path(artist.id) %></td>
						<td><%= artist.favorites.count %></td>
						<td><%= link_to "編集", edit_admin_artist_path(artist.id) %></td>
						<td><%= link_to "削除", admin_artist_path(artist.id),method: :delete,  data: { confirm: '削除してよろしいですか？' } %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>

		<%= link_to admin_artists_path do %>
			<button type="button" class="btn btn-default">一覧へ</button>
      	<% end %>

	</div>
</section>
<section class="cd">
	<h3>CD ランキング</h3>
	<div class="c-container">
		<table class="table">
			<thead>
				<tr>
					<th>アーティスト</th>
					<th>ジャケット写真</th>
					<th>タイトル</th>
					<th>ジャンル</th>
					<th>値段</th>
					<th>在庫</th>
					<th>リリース日</th>
					<th>売り上げ</th>
				</tr>
			</thead>
			<% @cds.each do |cd| %>
			<tbody>
				<tr>
					<td><%= cd.artist.name if cd.artist.present? %></td>
					<td><%= attachment_image_tag cd, :image, size: '30x30', format: 'jpeg', class: "", fallback: "no_image.png", alt: "No image" %></td>
					<td><%= link_to cd.title, cd_path(cd.id) %></td>
					<td><%= cd.genre %></td>
					<td><%= cd.price %></td>
					<td><%= cd.stock %></td>
					<td><%= cd.release %></td>
					<td><%= cd.proceed %></td>
					<td><%= link_to "編集", edit_admin_cd_path(cd.id) %></td>
					<td><%= link_to "削除", admin_cd_path(cd.id), method: :delete,  data: { confirm: '削除してよろしいですか？' } %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
		<%= link_to admin_cds_path do %>
		<button type="button" class="btn btn-default">一覧へ</button>
		<% end %>
	</div>
</section>

<h3>リクエスト一覧</h3>
<div class="r-container">



	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>受付日</th>
				<th>名前</th>
				<th>名前カナ</th>
				<th>アーティストネーム</th>
				<th>CDタイトル</th>
				<th>公式URL</th>
			</tr>
		</thead>

		<% @requests.each do |re| %>
		<tbody>
			<tr>
				<td><%= re.created_at.strftime('%Y/%m/%d') %></td>
				<td><%= link_to re.user.name, user_path(re.user.id) %></td>
				<td><%= re.user.kana %></td>
				<td><%= re.artist_name %></td>
				<td><%= re.song_name %></td>
				<td><%= link_to re.url, re.url, :target=>["_blank"] if re.url.present? %></td>
				<td><%= link_to "削除", user_request_path(id: re, user_id: re.user_id), method: :delete, data: {confirm: '削除してよろしいですか?'} %><td>

				</tr>
			</tbody>
			<% end %>
		</table>
		<%= link_to admin_requests_path do %>
		<button type="button" class="btn btn-default requestlist ">一覧へ</button>
		<% end %>
	</div>
</div>