config/routes.rb
Rails.application.routes.draw do

  get 'ship/new'
  get 'ship/index'
  get 'ship/edit'
  devise_for :users#, controllers: { registrations: 'registrations' }

  namespace :admin do
    get "/"=>"root#top"

    resources :users,only: [:index]
    resources :cds
    resources :artists
    resources :requests,only: [:index]
  end

    get '/top' => 'roots#top'
    root 'roots#top'
    resources :cds
    resources :artists,only: [:index, :show] do
        resources :favorites,only: [:create,:destroy]
    end
    resources :carts do
       resources :cartitems
    end
    post '/cartitems' => 'cartitems#create' , as: 'cartitem_create'

    resources :users,only: [:show,:edit,:update,:destroy] do
        get '/favorites' =>'users#favorites'
        resources :requests,only:[:create,:new, :destroy]
        resources :boughts do
          resources :boughtitems
        end
    end

    resources :ships

    get '/cd_search' =>'cds#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable;

         has_many :requests
         has_many :carts
         has_many :favorites
         has_many :boughts
         has_many :ships
         has_many :artists, through: :favorites
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin

  def index
		@users = User.all
  end
  def show
  end

  private
    def admin
       if user_signed_in?
         if current_user.admin?
         else
           redirect_to root_path
         end
       else
         redirect_to root_path
       end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
   #def destroy
    # if current_user.admin?
     #  flash[:error] = "You can't delete yourself"
      # redirect_to user_path(resource)
     #else
     #  super
     #end
   #end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    if @user == current_user or current_user.admin?
    else
       redirect_to user_path(current_user)
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user or current_user.admin?
    else
       redirect_to user_path(current_user), notice: '変更出来ませんでした'
    end
  end
  def update
     user = User.find(params[:id])
        user.update(user_params)
        redirect_to user_path(user.id), notice: '変更完了'
  end
  def destroy
    user = User.find(params[:id])
      if user.admin?
         redirect_to admin_users_path, notice: '管理者は削除出来ません'
      else
         user.destroy
         redirect_to admin_users_path, notice: '削除完了'
      end
  end

  def favorites
    @user = User.find_by(id: params[:user_id])
    @favorites = Favorite.where(user_id: @user.id).all
  end

  private
  def user_params
    params.require(:user).permit(:name,:kana,:tel,:address,:post,:email,:encrypted_password)
  end
  def admin_user
   redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="mypage_navi">
  <%= link_to user_favorites_path(user_id: @user) do %>
      <div>Favorite Artists</div>
    <% end %>
  <%= link_to user_boughts_path(user_id: @user) do %>
    <div>Purchase History</div>
  <% end %>
  <%= link_to user_path(id: @user) do %>
      <div>User Info</div>
  <% end %>
</div>

<div class="booksbody">
<h3>User Info</h3>
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-1">

<%= form_for(@user) do |f| %>

   <table class="table">
          <tr class="table2">
          <td class="table1 table2">名前</td>

           <td class="table4"> <%= f.text_field :name %></td>
         </tr>
         <tr class="table2">
         <td class="table1 "> 名前（カナ）</td>
          <td class="table4"><%= f.text_field :kana %></td>
        </tr>
        <tr class="table2">
        <td class="table1">郵便番号</td>
          <td class="table4"> <%= f.text_field :post %></td>
        </tr>
        <tr class="table2">
        <td class="table1">住所</td>
          <td class="table4"><%= f.text_field :address %></td>
        </tr>
        <tr class="table2">
        <td class="table1">電話番号</td>
          <td class="table4"><%= f.text_field :tel %></td>
        </tr>
        <tr class="table2">
        <td class="table1">メールアドレス</td>
          <td class="table4"><%= f.text_field :email %></td>
        </tr>
        <tr class="table2">
        <td class="table1">パスワード</td>
          <td class="table4"><%= f.text_field :password %></td>
        </tr>


      </table>
<div class="clearfix back2">
      <%= button_to '戻る', user_path, method: :get, class: 'btn btn-default botan1 back1' %>
      <%= f.submit "保存", class: "btn btn-default  botan1 back3" %>
      </div>
        <% end %>



     </div>
     </div>
     </div>
     </div>

app/views/users/favorites.html.erb
<div class="mypage_navi">
	<%= link_to user_path(id: @user) do %>
    	<div>User Info</div>
    <% end %>
	<%= link_to user_boughts_path(user_id: @user) do %>
		<div>Purchase History</div>
	<% end %>

	<%= link_to new_user_request_path do %>
		<div>Requst</div>
	<% end %>
</div>
<div class="container mypage">
	<section class="mypage-main-title">
		<h3 class="mypage-main-title-text">My Favorite Artists<br>
		<i class="fas fa-heart"></i></h3>
	</section>

	<section class="mypage-artists-index">
		<div class="m-a-i-container clearfix">
			<% @favorites.each do |favorite| %>
			<div class="m-a-i-box">
				<% artist = Artist.find(favorite.artist_id) %>
				<%= link_to artist_path(artist.id) do %>
					<%= attachment_image_tag artist, :image, class:"m-a-i-img" %>
				<div class="mask">
              		<div class="caption">
               			<h2 class="top-artist-name"><%= artist.name %></h2>
              		</div>
             	</div>
				<% end %>
			</div>
			<% end %>
		</div>
	</section>
</div>

app/views/users/show.html.erb
<div class="mypage_navi">
  <%= link_to user_favorites_path(user_id: @user) do %>
      <div>Favorite Artists</div>
    <% end %>
  <%= link_to user_boughts_path(user_id: @user) do %>
    <div>Purchase History</div>
  <% end %>
  <%= link_to new_user_request_path(user_id: @user) do %>
    <div>Requst</div>
  <% end %>
</div>
<div class="booksbody">

  <div>
    <% if notice %>
    <p id="notice"><%= notice %></p>
    <% end %>
  </div>

  <h3>User Info</h3>
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-1">

<!-- <div class="usershow col-xs-offset-3"></div> -->

   <table class="table">
          <tr class="table2">
          <td class="table1 table2">名前</td>

           <td class="table3"> <%= @user.name %></td>
         </tr>
         <tr class="table2">
         <td class="table1 "> 名前（カナ）</td>
          <td class="table3"><%= @user.kana %></td>
        </tr>
        <tr class="table2">
        <td class="table1">郵便番号</td>
          <td class="table3"><%= @user.post %></td>
        </tr>
        <tr class="table2">
        <td class="table1">住所</td>
          <td class="table3"><%= @user.address %></td>
        </tr>
        <tr class="table2">
        <td class="table1">電話番号</td>
          <td class="table3"><%= @user.tel %></td>
        </tr>
        <tr class="table2">
        <td class="table1">メールアドレス</td>
          <td class="table3"><%= @user.email %></td>
        </tr>
        <tr class="table2">
        <td class="table1">パスワード</td>
          <td class="table3"><%= @user.password %></td>
        </tr>
      <% if current_user.admin?%>
        <tr class="table2">
        <td class="table1">こいつ嫌い</td>
          <td class="table3"><%= link_to "削除", user_path, method: :delete, data: {confirm: '退会させてよろしいですか?'}, class: "taikai" %></td>
        </tr>
      <% else %>
        <tr class="table2">
        <td class="table1">退会</td>
          <td class="table3"><%= link_to "退会希望の方はこちら", user_registration_path, method: :delete, data: {confirm: 'go to hell?'}, class: "taikai" %></td>
        </tr>
      <% end %>

      </table>

        <%=button_to '編集', edit_user_path ,method: :get, class: 'btn btn-default botan1' %>

     </div>
     </div>
     </div>
     </div>