config/routes.rb
Rails.application.routes.draw do

  get 'ship/new'
  get 'ship/index'
  get 'ship/edit'
  devise_for :users#, controllers: { registrations: 'registrations' }

  namespace :admin do
    get "/"=>"root#top"

    resources :users,only: [:index]
    resources :cds
    resources :artists
    resources :requests,only: [:index]
  end

    get '/top' => 'roots#top'
    root 'roots#top'
    resources :cds
    resources :artists,only: [:index, :show] do
        resources :favorites,only: [:create,:destroy]
    end
    resources :carts do
       resources :cartitems
    end
    post '/cartitems' => 'cartitems#create' , as: 'cartitem_create'

    resources :users,only: [:show,:edit,:update,:destroy] do
        get '/favorites' =>'users#favorites'
        resources :requests,only:[:create,:new, :destroy]
        resources :boughts do
          resources :boughtitems
        end
    end

    resources :ships

    get '/cd_search' =>'cds#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :cds, inverse_of: :artist, dependent: :destroy
	has_many :favorites, dependent: :destroy
	accepts_nested_attributes_for :cds
	attachment :image
	has_many :users, through: :favorites

	def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Artist.where(['name LIKE ?', "%#{search}%"])
	    end
	end

	# def favorited_by?(user)
          # favorites.where(user_id: user.id).exists?
    # end

end

app/models/bought.rb
class Bought < ApplicationRecord
	belongs_to :user#, optional: true
	has_many :boughtitems, dependent: :destroy

	enum status: { in_preparation: 0, shipped: 1, delivery_completed: 2}
	enum ship: { home: 0, new: 1, registered1: 2}, _suffix: true

	def total_price
		boughtitems.to_a.sum { |item| item.total_price }
	end

	default_scope -> { order(created_at: :desc) }
end

app/models/boughtitem.rb
class Boughtitem < ApplicationRecord
	belongs_to :bought
	belongs_to :cd

	def total_price
		cd.price * quantity
	end
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user, optional:true
	has_many :cartitems, dependent: :destroy, inverse_of: :cart
    accepts_nested_attributes_for :cartitems, reject_if: :all_blank, allow_destroy: true

	def add_cd(cd_id)

		current_item = cartitems.find_by_cd_id(cd_id)

		if current_item
			current_item.quantity += 1
		else
			current_item = cartitems.build(cd_id: cd_id)
		end
		current_item

	end

	def total_price
		cartitems.to_a.sum { |item| item.total_price }
	end

end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
	belongs_to :cart, optional:true, inverse_of: :cartitems
	belongs_to :cd, optional:true

	def total_price
		cd.price * quantity
	end
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :artist, optional:true, inverse_of: :cds
	has_many :discs, inverse_of: :cd
	has_many :boughtitems
	has_many :cartitems
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true
	attachment :image

  enum genre: { J_pop: 0, Roock: 1, EDM: 2, Metal: 3, Jazz: 4, Classic: 5, Country: 6, Rap: 7 }


 def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       Cd.where(['genre LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    end
 end

	# 商品を破棄する際のフックメソッドを登録する
    # destroy()が実行される前に、Railsが自動的に実行する
    # 戻り値がfalseであれば、destroy()は実行されない
    # (リフレクションで呼出されるらしい)
    before_destroy :referenced_by_cartitem

    private

    def referenced_by_cartitem
      # 関連する品目が空でないか検証
      if cartitems.empty?
        return true
      else
        errors.add(:base, "品目が存在します")
        return false
      end
    end

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :cd, inverse_of: :discs
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :artist

	validates :artist_id, :uniqueness => {:scope => :user_id}
	# validates :user_id, :uniqueness => {:scope => :article_id}

end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/ship.rb
class Ship < ApplicationRecord
	belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc, inverse_of: :songs


def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
    	Song.where(['name LIKE ?', "%#{search}%"])


    end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable;

         has_many :requests
         has_many :carts
         has_many :favorites
         has_many :boughts
         has_many :ships
         has_many :artists, through: :favorites
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  protect_from_forgery except: :create

  def index
      @carts = Cart.all
  end

  def show
      @bought = Bought.new
      @user = User.find_by(id: current_user.id)
      if @user.ships.present?
        @ship_last = Ship.where(user_id: @user).last
      else
      end
  end

  def new
      @cart = Cart.new
  end

  def edit
  end

  def create

      @bought = Bought.new(bought_params)
      @bought.user_id = current_user.id

      @cart = current_cart
      @cart.user_id = current_user.id

      @user = User.find_by(id: current_user.id)
      @ship = Ship.where(user_id: @user).last

      if @bought.ship == "home"
         @bought.name = current_user.name
         @bought.kana = current_user.kana
         @bought.post = current_user.post
         @bought.address = current_user.address
         @bought.tel = current_user.tel
      end

      if @bought.ship == "new"
           @ship = Ship.new
           @ship.user_id = current_user.id
           @ship.name = @bought.name
           @ship.kana = @bought.kana
           @ship.post = @bought.post
           @ship.address = @bought.address
           @ship.tel = @bought.tel
           @ship.save
      end

      if @bought.ship == "registered1"
         @bought.name = @ship.name
         @bought.kana = @ship.kana
         @bought.post = @ship.post
         @bought.address = @ship.address
         @bought.tel = @ship.tel
      end
       if @bought.save

           @cart.cartitems.each do |item|

              @boughtitem = @bought.boughtitems.build
              @boughtitem.cd_id = item.cd_id
              @boughtitem.quantity = item.quantity
              @boughtitem.subtotal = item.cd.price * item.quantity

              @cd = item.cd
              @cd.stock = @cd.stock - item.quantity
              @cd.proceed += item.quantity
              @cd.save

              @artist = @cd.artist
              @artist.proceed += @cd.proceed
              @artist.save

              @boughtitem.save
           end
           Cart.destroy(session[:cart_id])
           session[:cart_id] = nil
           redirect_to user_boughts_path(current_user.id), notice: 'ご注文ありがとうございました。'
       end
  end

  def update
      if @cartitem.update(cart_params)
         redirect_to @cart, notice: 'Cart was successfully updated.'
      else
        render :editend
      end
  end

  def destroy
      @cart = current_cart
      @cart.destroy
      session[:cart_id] = nil
      redirect_to cds_url, notice: 'カートが空になりました。'
  end

  private
    def set_cart
        @cart = Cart.find(params[:id])
    end

    def cart_params
        params.fetch(:cart, {}).permit(:id, cartitems:[:id, :quantity, :cart_id, :cd_id, :_destroy])
    end

    def bought_params
        params.require(:bought).permit(:name, :kana, :post, :address, :tel, :status, :ship)
    end

    def ship_params
        params.require(:ship).permit(:name, :kana, :post, :address, :tel)
    end

    def user_params
    params.require(:user).permit(:name,:kana,:tel,:address,:post,:email)
    end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/ship_helper.rb
module ShipHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container cart">
  <div>
    <% if notice %>
    <p id="notice"><%= notice %></p>
    <% end %>
  </div>

  <div>
    <h3>Ｃａｒｔ<br>
      <div class= "i fas fa-shopping-cart cart_icon"></div>
    </h3>
  </div>

   <div class="cart_btn_box clearfix">
    <div class="btn_box clearfix">
      <div class="cart_btn2">
        <%= button_to '買い物を続ける', cds_path, method: :get, class: 'fbtn' %>
      </div>
      <div class="cart_btn1">
        <%= button_to 'カートを空にする', @cart, method: :delete, data: {confirm: 'カートを空にして本当によろしいですか？'}, class: 'fbtn' %>
      </div>
    </div>
   </div>

   <div class="cart_box clearfix">

      <div class="cart_price">
        <font size="5">総計：<%= (@cart.total_price).to_i %>円</font>
      </div>

      <% @cart.cartitems.each do |item| %>
    		<div class="cart_item clearfix">

    			<div class="cart_jaket">
    				<%= attachment_image_tag item.cd, :image,  format: 'jpeg', fallback: "no_image.png", alt: "No image", size: '200x200' %>
    			</div>

    			<div class="cart_cds">

            <p><%= item.cd.artist.name %></p>
            <p><%= item.cd.title %></p>
            <div>値段：<%= (item.cd.price).to_i %>円</div>
    				<div>
    				  <%= form_for([@cart, item]) do |item| %>
                個数：
    					  <%= item.number_field :quantity, class: "cart_quantity" %>
                          <%= item.submit "更新" %>
    				  <% end %>
    				</font></div>
            <div class="clearfix">
              小計：<%= (item.total_price).to_i %>円
              <%= button_to '削除', cart_cartitem_path(@cart, item), method: :delete,class: 'fbtn' %>
            </div>
    		  </div>
        </div>
      <% end %>
   </div>

    <br>
  <div class="cart_ship">
    <h2 class="ship_title">お届け先</h2>

     <%= form_for(@bought, :url => {:controller => :carts, :action => :create}, :html => { :method => :post }) do |f| %>

    <table class="table table-hover table-inverse">
      <div class="form-group container">
        <div class="field row col-xs-4">
           <tr>
            <th>お届け先選択</th>
            <td>
              <%= f.radio_button :ship, :home, checked: "checked" %>
              <%= f.label :自宅, class: "ship_label" %>
              <%= f.radio_button :ship, :new %>
              <%= f.label :新しいお届け先, class: "ship_label" %>
              <% if @ship_last.present?%>
               <%= f.radio_button :ship, :registered1 %>
               <%= f.label :最近配送した住所, class: "ship_label" %>
              <% else %>
              <% end %>
            </td>
           </tr>
        </div>
      </div>
    </table>

    <table class="table table-hover table-inverse">
　　　　　　<!-- 新規お届け先 -->
      <div class="form-group container">
        <div class="field row col-xs-12">
           <tr class="ship ship02">
            <th><%= f.label :名前 %></th>
            <td><%= f.text_field :name, :placeholder => "大内　誠" %></td>
           </tr>

           <tr class="ship ship02">
            <th><%= f.label :カナ %></th>
            <td><%= f.text_field :kana, :placeholder => "オオウチ　マコト" %></td>
           </tr>

           <tr class="ship ship02">
            <th><%= f.label :郵便番号 %></th>
            <td>
              <input type="text" name="bought[post]" id="bought_post" size="10" maxlength="8" placeholder="2600852" onKeyUp="AjaxZip3.zip2addr(this,'','bought[address]','bought[address]');">
            </td>
           </tr>

           <tr class="ship ship02">
            <th><%= f.label :住所 %></th>
            <td>
              <input type="text" name="bought[address]" id="bught_address" size="40" placeholder="千葉県千葉市中央区青葉町1-10-1マコちゃんハウス">
            </td>
           </tr>

           <tr class="ship ship02">
            <th><%= f.label :電話番号 %></th>
            <td><%= f.text_field :tel, :placeholder => "09011112222" %></td>
           </tr>
        </div>
        <!-- 登録済み住所１ -->
        <% if @ship_last.present?%>
        
        <div class="field row col-xs-12">
           <tr class="ship ship03">
            <th>名前</th>
            <td><%= @ship_last.name %></td>
           </tr>

           <tr class="ship ship03">
            <th>カナ</th>
            <td><%= @ship_last.kana %></td>
           </tr>

           <tr class="ship ship03">
            <th>郵便番号</th>
            <td>
              <%= @ship_last.post %>
            </td>
           </tr>

           <tr class="ship ship03">
            <th>住所</th>
            <td>
              <%= @ship_last.address %>
            </td>
           </tr>

           <tr class="ship ship03">
            <th>電話番号</th>
            <td><%= @ship_last.tel %></td>
           </tr>
        </div>
        <% else %>
        <% end %>
      </div>
    </table>
  </div>
  	    <div class="create_btn">
  		    <%= button_to '注文をする', carts_path(@cartitem), method: :post, class: 'fbtn' %>
  	    </div>
     <% end %>
</div>

<script src="https://ajaxzip3.github.io/ajaxzip3.js" charset="UTF-8"></script>
<script src="jquery-3.3.1.min.js"></script>
<script src="cart.js"></script>